name: Harvest & Spice
tagline: Plant-Powered Catering
description: Plant-powered seasonal meals celebrating Mediterranean flavors through California farm bounty.

contact:
  email: harvestandspice@gmail.com
  phone: 510-365-8348
  address: Oakland, CA
  service_area: Bay Area (Oakland-based) - Berkeley, SF, Marin, Peninsula, Santa Cruz Mountains
  instagram: https://instagram.com/harvestandspice
